### ISSUE TITLE
Not able to render Font Family while conversion to PNG & JPG

### ISSUE THREAD

**Issue by abhilab** [svg-net/SVG#1059] opened 2023-05-26 09:14 UTC
#### Description
I added Font Face to SVG, Font family shows in SVG Preview, but when I convert SVG to Bitmap using Draw method, then save the Bitmap to PNG, JPG. It does not render the font.
NOTE: The font shows on SVG but not in PNG, JPG

#### Example data
**Code in SVG:**
<defs>
		<style>
			@font-face {
			font-family:Segoe Pro Bold;
			src: url("data:font/truetype;charset=utf-8;base64, my fonts base64 code") format('truetype');
			}
		</style>
</defs>

**Code in C#**
 Bitmap bmp = mySvg.Draw(pixelWidth, pixelHeight);
bmp.Save(@"Filename.jpeg", jgpEncoder,myEncoderParameters);

#### Used Versions

SVG version used: 3.4.4

Please help me out, I am stuck at the end of deadline, all my work is complete for image generation, only the Font family is not showing. Thanks in advance.

**Comment by mrbean-bremen** [comment] 2023-05-26 10:30
Duplicate of #1060.

**Closed by mrbean-bremen** 2023-05-26 10:30 UTC

**Comment by abhilab** [comment] 2023-05-26 10:43
I wish to get a reply ASAP, hence the duplicate.

**Comment by mrbean-bremen** [comment] 2023-05-26 11:05
Duplicates don't get you an answer faster. 
I see that you are new to GitHub - you have to understand that the people contributing and answering here do this in their free time, and getting some ASAP message or double-posting it usually will not help - on the contrary, most people will may get annoyed.

**Comment by abhilab** [comment] 2023-05-26 11:07
Understood, thanks.
Actually I posted one as a “New Issue” and second one in QnA section.
Won’t happen again. Thanks for the heads up.
