### ISSUE TITLE
NO_SDC breaks Fill-Property

### ISSUE THREAD

**Issue by just0x** [svg-net/SVG#962] opened 2022-03-21 09:55 UTC
#### Description
Using the Fill-Property of SvgElement does not work, when compiling with NO_SDC.

If you specify `new SvgColourServer(Color.White)`, using SvgDocument.Write(Stream stream) `style="fill:'White'"` will be written to the stream, which is not valid in a xml/html sense.
As far as i understand, the probem lies in `SvgColourConverter.ConvertTo`. The `#if !NO_SDC` needs an else-branch that renders colors to valid xml/html.

#### Example data
Following code
```
var doc = new SvgDocument();
doc.Children.Add(new SvgRectangle
{
    Y = 0,
    X = 0,
    Height = 100,
    Width = 100,
    Fill = new SvgColourServer(Color.White),
});

using (var stream = File.OpenWrite(Path.GetTempFileName()))
{
    doc.Write(stream);
}
```
produces a file containing following invalid svg:

```
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xml="http://www.w3.org/XML/1998/namespace">
  <rect x="0" y="0" width="100" height="100" style="fill:'White';" />
</svg>
```

#### Used Versions
origin/master version 3.4.1 on Win10 .NET5

**Comment by mrbean-bremen** [comment] 2022-03-21 18:18
The NO_SDC flag is there to compile without `System.Drawing.Common`, but to make that work you need an implementation that provides a replacement. @wieslawsoltes is working on doing this using his [Svg.Skia](https://github.com/wieslawsoltes/Svg.Skia), but that is work in progress and not ready to use yet.

CC @wieslawsoltes

**Comment by mrbean-bremen** [comment] 2022-04-03 16:50
Closing, this is not a bug. `NO_SDC` is undocumented and not ready to be used.

**Closed by mrbean-bremen** 2022-04-03 16:50 UTC
