### ISSUE TITLE
Svg on opening loads nothing in .NET Core 2.2

### ISSUE THREAD

**Issue by thedonciuxx** [svg-net/SVG#427] opened 2019-03-03 13:37 UTC
Hi, I am using the .NET Core 2.2 and am using the latest NuGet version of the SVG Package (2.4.2),

I am getting no errors when running the code like I saw on other issue reports, but for me the svg's are "empty". I'm trying to load / open an svg and drawing it, but it draws nothing.

I modified my code to save each loaded svg to a png image, this is the result: (The color is black, but that's a windows explorer thing, they're actually empty, but with defined size)
![explorer_2019-03-03_11-55-44](https://user-images.githubusercontent.com/13348029/53695913-0babb000-3dca-11e9-84ad-4e98c4a001de.png)

**Comment by mrbean-bremen** [comment] 2019-03-03 15:51
.NET Core is not yet supported in 2.4.2 (as you probably know, as you have commented under the [respective PR](https://github.com/vvvv/SVG/pull/415)), but hopefully will be in soon.

**Comment by thedonciuxx** [comment] 2019-03-03 16:32
Ah, so you've seen my comment... Still it's been a really long time since the original author of the pr made any changes, I really hope the conflicts get resolved and bugs get fixed soon to merge! 😄

**Comment by mrbean-bremen** [comment] 2019-03-03 18:50
Yeah, I hope so, too... maybe I will resolve the conflicts myself, but I really would like to get a response from the author first.
This issue is basically a duplicate of #400 and #248, hopefully to be resolved soon.

**Comment by thedonciuxx** [comment] 2019-03-09 22:10
I don't know if I should open a different issue or update this one, but the build which should support the .NET Core 2.2 is still in need of bug fixing...

I ran the published linux app on a Ubuntu emulator (VirtualBox to be specific) and got this error:
```
System.NullReferenceException: Object reference not set to an instance of an object.
at Svg.SvgDocument.Open[T](String path, Dictionary`2 entities)
```

I know that it loads the file, because one time I forgot to add it and it said that file wasn't found (or something like that can't remember exactly)

**Comment by mrbean-bremen** [comment] 2019-03-10 08:54
Well, this is work in progress, and l haven't done anything apart from conflict resolving and getting the AppVeyor tests running again. I planned to have a closer look this weekend, but I caught a cold and am not really up to it at the moment.
Also, the CI tests are run under Windows only. It would certainly make sense to add Travis.CI tests for Linux and Mac OS. An, help is welcome...

**Comment by mrbean-bremen** [comment] 2019-03-14 16:26
So I mostly got rid of the cold and may have another look at this somewhere in the next days, but I know nothing about using .NET Core under Linux. Can you give me some hints about your usage?
You mentioned that you used the published linux app - you mean you own app?

**Comment by thedonciuxx** [comment] 2019-03-18 21:39
Sorry was off my computer myself 😅, I am trying to load the svg files with specified dimensions. Then I turn that in to a Bitmap object. For the test above I drew them one by one right after they're loaded.

**Comment by mrbean-bremen** [comment] 2019-03-19 07:14
Thanks! What I meant was - I have no idea how to setup .NET under Linux, never used that, as I'm working under Windows, though I could give it a try - thus I would like some pointers as how it is commonly used / setup. Also it would make sense to setup unit tests under Linux using Travis.CI later.

That being said, I will be away most of the next week (and I'm still fighting with the aftermath of the virus I caught last week), so I'm not likely to get anything done very soon.

**Comment by thedonciuxx** [comment] 2019-03-25 16:41
Hope you are feeling better and stronger after the virus ^^

Now I don't have that much experience in C# and the .NET Core, but hope this helps:
 • I am loading svgs by using SvgDocument class and Open(string) function.
 • The function appears to contain this in it's body > `return Open<SvgDocument>(path, null);` and that links to a different function Open<T>(string path, Dictionary<string, string> entities) where T : SvgDocument, new()

And that's where the error occurs. Hopefully this is enough to recreate my use?

I know I'm not being that helpful, but I don't know what I could do to help. 😞

**Comment by mrbean-bremen** [comment] 2019-03-27 20:33
I'm back and feeling stronger now, thanks ;) 
My basic problem is just that I haven't used .NET under Linux, so I just wanted to know how to set up this, but I can find documentation on that myself. Maybe I will have another look at the weekend...

**Comment by thedonciuxx** [comment] 2019-03-28 19:11
I'm a Windows user myself. I to test if my app works on Linux use VirtualBox. (I don't know if you used VBox before, just in case you haven't here's how to get Linux + .NET Core on it `\/`)

I've set up a machine for Ubuntu 64bit, launched with a virtual optical disk file with Ubuntu setup.
Once that was done I ran these through the terminal to install the .NET Core
```
sudo add-apt-repository universe
sudo apt-get install apt-transport-https
sudo apt-get update
sudo apt-get install aspnetcore-runtime-2.2
```

Once that was done the machine was ready to be used for testing if a .NET Core application published for Linux works ^^

Hope this helps

**Comment by thedonciuxx** [comment] 2019-03-28 19:11
(I closed it by accident oops)

**Comment by mrbean-bremen** [comment] 2019-03-28 19:40
Ok, thanks :) I actually have a Linux partition on my notebook (Ubuntu) which I admittedly use rarely, so I can have a try. Maybe I will get to it at the weekend, though I can't promise anything (I'm a bit short on free time at the moment).

**Comment by ScarletKuro** [comment] 2019-04-23 10:21
You actually don't need Linux installed on your notebook to test the code. You can wrap your application in docker which both Rider and Visual Stuido 2017 supports for netcore applications. It would allow you to easily switch between environments and debug the code in the VS.

**Comment by mrbean-bremen** [comment] 2019-04-23 18:18
Thanks, @ScarletKuro! As you may have noticed, I took a longer timeout from this stuff (due to personal time constraints). I will see if I can come back to this soon, though I wouldn't mind If anyone else wanted to have a go :)

**Comment by chucker** [comment] 2019-05-09 18:38
I've looked into this. The `NullReferenceException` _probably_ ultimately occurs because the library never renders anything valid, as it fails very early on in trying to determine the system DPI, for which it uses Windows-specific code. I've stubbed code that will work on macOS and Linux, but a proper solution will require a greater re-think.

**Comment by mrbean-bremen** [comment] 2019-05-09 18:45
Ah, I forgot about the Windows-specific code - thanks, tht explains a lot!

**Comment by mrbean-bremen** [comment] 2019-05-13 08:54
@thedonciuxx - can you please check this in current master?

**Comment by thedonciuxx** [comment] 2019-05-13 19:49
```
System.OutOfMemoryException: Out of memory.
   at System.Drawing.Graphics.FillPath(Brush brush, GraphicsPath path)
   at Svg.SvgVisualElement.RenderFill(ISvgRenderer renderer)
   at Svg.SvgVisualElement.RenderFillAndStroke(ISvgRenderer renderer)
   at Svg.SvgVisualElement.Render(ISvgRenderer renderer, Boolean renderFilter)
   at Svg.SvgElement.RenderChildren(ISvgRenderer renderer)
   at Svg.SvgVisualElement.Render(ISvgRenderer renderer, Boolean renderFilter)
   at Svg.SvgElement.RenderChildren(ISvgRenderer renderer)
   at Svg.SvgVisualElement.Render(ISvgRenderer renderer, Boolean renderFilter)
   at Svg.SvgElement.RenderChildren(ISvgRenderer renderer)
   at Svg.SvgElement.Render(ISvgRenderer renderer)
   at Svg.SvgFragment.Render(ISvgRenderer renderer)
   at Svg.SvgDocument.Draw(Int32 rasterWidth, Int32 rasterHeight)
```

Is this normal or did I mess up some settings on my Virtual Machine?

It's running on 4 GB of memory and my project (running on my Windows machine) uses about 200 MB.

**Comment by mrbean-bremen** [comment] 2019-05-14 05:06
Doesn't look normal :/ 
Does this happen with all your images, or with specific ones? Out of memory errors [can actually happen](https://github.com/vvvv/SVG/wiki/Q&A#why-does-my-application-crash-with-cannot-allocate-the-required-memory) for large bitmaps, though I doubt that this is your problem...

**Comment by thedonciuxx** [comment] 2019-05-14 17:55
There is one svg file which is causing problems... But I have no idea why... There are much bigger and more detailed svgs that load perfectly...

This is the file (I had to zip it as Github doesn't allow svg uploads :/ )
[barrel.zip](https://github.com/vvvv/SVG/files/3179129/barrel.zip)

Also noticed a problem?
On Linux outlines are not drawn.

But it's running now! So that's amazing progress! `^^`

**Comment by mrbean-bremen** [comment] 2019-05-14 18:34
Hm, the svg doesn't show anything in any browser for me, nor does it in the SVG viewer.

**Comment by thedonciuxx** [comment] 2019-05-14 18:47
Uhh forgot to mention...

The svg is scalled to be I think below 1px wide.

My project makes an image using the svgs and info on which tile is placed where.

One of the options in my project is being able to choose a tileSize.
Every tile is scaled to fit the 1px wide tiles
And if someone wanted to choose a tileSize of, for example, 30px
Then I just multiply the size of the image by 30. (Load image -> Draw (make raster object) with variables 30x bigger)

**Comment by mrbean-bremen** [comment] 2019-05-14 19:00
No wonder I didn't see it... there are problems with [very small elements under Windows](https://github.com/vvvv/SVG/issues/278) with GDI+, which causes OutOfMemory exceptions - looks like they ported the bug to Linux...

**Comment by mrbean-bremen** [comment] 2019-05-28 18:06
@thedonciuxx - your problem with the small element is probably a duplicate of [the mentioned problem](https://github.com/vvvv/SVG/issues/278), which is ultimately a bug in GDI+ (or, in this case, probably in libgdiplus.
Can you elaborate on the other problem you saw (missing outline)?

**Comment by thedonciuxx** [comment] 2019-06-25 12:55
I'm back. Was away.

I tried to run the code, but noticed some odd behavior...

The `barrel.svg` file seems to still cause an `System.OutOfMemoryException`, but without it the code runs.

However that's not all. Some outlines just aren't draw for some reason. And it's for specific svg files.

This could be a problem on my end, but these issues weren't there before using the built code you referenced...

**Comment by mrbean-bremen** [comment] 2019-06-25 18:59
Ok, welcome back :) Let us know if you find something.

**Comment by windowzz** [comment] 2021-09-21 09:56
@mrbean-bremen
could you plz take a look into this
https://github.com/svg-net/SVG/issues/898

**Comment by windowzz** [comment] 2021-09-21 09:57
@mrbean-bremen 
could you plz take a look into this https://github.com/svg-net/SVG/issues/898

**Comment by mrbean-bremen** [comment] 2021-09-21 19:53
Closing this as stale - please open new issues if needed.

**Closed by mrbean-bremen** 2021-09-21 19:53 UTC
Labels: enhancement, platform-support

**Comment by mrbean-bremen** [comment] 2021-10-08 19:29
Please open a new issue for this - hopefully someone with access to a Mac can help with this.
